var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  x!!xx         ",
   "                                                   xx             x!x           ",
   "                                    o o      xx                   x!x           ",
   "  xxx                                  y                xx!!!xx      xxx!!!!xx  ",
   "  x                              xxxx                                           ",
   "  x                                                                          xx ",
   "  x                                      o o                                  x ",
   "  x                     o                  y                            T     x ",
   "  x                                      xxxxx                         xx  o  x ",
   "  x            L                                                              x ",
   "  x  @       xxxx                                                xxxxx        x ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxx!!!!!!!!xxxxxxxxx!!!!!xxxxxxx   xxxxxxxxxx",
   "                              x   x    !!!!!!         x!!!!x                    ",
   "                              x!!!x                   x!!!x                     ",
   "                              x!!!x                   x!!x                      ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                x!x           ",
   "                                                                                        x!x                   ",
   "                                                                      o   o   o  x!x                          ",
   "                                                       x     o   o                                    xx!x    ",
   "                                                          x                                xxxxxxxxxxxxxxx!!x ",
   "                                                          x     x   x                               !!!!!!!xx ",
   "                                                                                        xxxxxxxxxxxxxxxx      ",
   "                                                                    xxxx!!!!!xxxx                    v        ",
   "                                                                                                              ",
   "                                               x     x          xxxxxxx          xxx         xxx              ",
   "                                               x     x                                   x x         x x      ",
   "                                               x     x                           x         x                  ",
   "                                               x     x                                 xx        x            ",
   "                                               xx    x                         x         x                    ",
   "                                               x     x      o  o     x   x            x         x             ",
   "                              xxx   xxx        x     x               x   x       x         x                  ",
   "                         x             x     x     xxxxxx    x   x   xxxxxxxxx       x                        ",
   "                   x o x     x     x    xx               x   x   x               x                            ",
   "     @             x   x          x     x               x   x   x               x                             ",
   "    xxx            x   x          x     x               x   xxxxx   xxxxxx      x                             ",
   "    x x                        xx o xx         x     x               x     o     x x         x                ",
   "!!!!x x!!!!!!xxxxxx!xxxx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                ",
   "!!!!x x!!!!!!x         x!!!!!x    o                x    !!!!!!xx !                    xx     xx               ",
   "!!!!x x!!!!!!x           !!!!                              !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                              ",
   "!!!!x x!!!!!!x               xxxxxxxxx  !                                                                     ",
   "!!!!x x!!!!!!x                                                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                                        !!!        !!!  xxx                                   ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx                 x          x                                         ",
   "                           xxxxx           x   x                 x                  oooo   x       xxx        ",
   "                                        x                 x          x      x!!!x                             ",
   "                     xxx                 x   x      xxxxxxxxxxxx       xxx                                    ",
   "                                     xx          xx      x   x      x                                         ",
   "                              xxxx        x   xxxxxxxxx   xxxxxxxx              x x                           ",
   "                         xxxx             x   x           x                    x!!!x                          ",
   "                               xxxx       x   x           x                     xxx                           ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                         xxx          x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx            xxx                         ",
   "                                     xx   xx          x                x!!!x                                  ",
   "                              o   o   x   x           x     x                      xxv        xxx             ",
   "                                      x   x           x              x    x!!!x                               ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                       xxxxxx      x x x x xxx x          x!!!!!!!!!!!!!!x                                    ",
   "                             x                        xxxxxxxxxxxxxxxxxxxxxxx                                 ",
   "            xxxx           xx           xx                                         xxx               T        ",
   "  xxx                              x     x                                    x!!!x                xxx xxxxx  ",
   "  x x                     xxxxxx       x    xxx    x                                          xxx        x x  ",
   "  x                               xxx          xxxxxxx                        xxxxx                       x   ",
   "  x          xxxxxx             x                                         x   x                               ",
   "  x                    xxxxx       xx          x                              x x x                        x  ",
   "  x                                xx             |xxxx|    |xxxx|     xxx xxx                     x          ",
   "  x             xxxx                   o o                                   x         xxx                 x  ",
   "  x                      xxx                                               xxx          x!!!x          x   x  ",
   "  x                                xxx            xx   x                             x x        xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                           xxx      xxx       xxxxxxxx          xxx      xxx                                  ",
   "                           xxx      xxx       xxxxxxxxx         xxx      xxx                                  ",
   "                           xxx      xxx     xx         xx       xxx      xxx                                  ",
   "                           xxx      xxx    xx           xx      xxx      xxx                                  ",
   "                             xxx   xxx    xx             xx       xxx   xxx                                   ",
   "                                xxx      xxxxxxxxxxxxxxxxxxx         xxx                                      ",
   "                                xxx     xx                 xx        xxx                                      ",
   "                                xxx    xx                   xx       xxx                                      ",
   "                                xxx   xx                     xx      xxx                                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
